version: '3.8'

services:
  db:
    build:
      context: ./databases
      dockerfile: Dockerfile-db
    container_name: userlogin-db
    environment:
      MYSQL_DATABASE: userlogin
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_USER: taha
      MYSQL_PASSWORD: password123
    ports:
      - "3307:3306"  # Changed to avoid conflict with local MySQL
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    ports:
      - "8080:8080"  
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: userlogin
      DB_USER: taha
      DB_PASSWORD: password123

volumes:
  db_data:
