FROM mysql:8.0

# Copy MySQL configuration and initialization files
COPY my.cnf /etc/mysql/my.cnf
COPY init.sql /docker-entrypoint-initdb.d/
COPY userlogin_comment.sql /docker-entrypoint-initdb.d/
COPY userlogin_genre.sql /docker-entrypoint-initdb.d/
COPY userlogin_language.sql /docker-entrypoint-initdb.d/
COPY userlogin_movie.sql /docker-entrypoint-initdb.d/
COPY userlogin_moviegenre.sql /docker-entrypoint-initdb.d/
COPY userlogin_movielanguage.sql /docker-entrypoint-initdb.d/
COPY userlogin_user.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3308
